from django.urls import path

from . import views

urlpatterns = [
    path(
        'mine/',
        views.ManageCourseListView.as_view(),
        name='manage_course_list',
    ),
    path(
        'create/',
        views.CourseCreateView.as_view(),
        name='course_create',
    ),
    path(
        '<pk>/edit/',
        views.CourseUpdateView.as_view(),
        name='course_edit',
    ),
    path(
        '<pk>/delete/',
        views.CourseDeleteView.as_view(),
        name='course_delete',
    ),
    path(
        '<pk>/module/',
        views.CourseModuleUpdateView.as_view(),
        name='course_module_update',
    ),
    path(
        'module/<int:module_id>/lessons/',
        views.ModuleLessonUpdateView.as_view(),
        name='module_lesson_update',
    ),
    path(
        'module/<int:module_id>/tests/',
        views.ModuleTestUpdateView.as_view(),
        name='module_test_update',
    ),
    path(
        'module/<int:module_id>/assignments/',
        views.ModuleAssignmentUpdateView.as_view(),
        name='module_assignment_update',
    ),
    path(
        'test/<int:test_id>/questions/',
        views.TestQuestionUpdateView.as_view(),
        name='test_question_update',
    ),
    path(
        'question/<int:question_id>/answers/',
        views.QuestionAnswerUpdateView.as_view(),
        name='question_answer_update',
    ),
    path(
        'module/<int:module_id>/content/<model_name>/create/',
        views.ContentCreateUpdateView.as_view(),
        name='module_content_create',
    ),
    path(
        'module/<int:module_id>/content/<model_name>/<id>/',
        views.ContentCreateUpdateView.as_view(),
        name='module_content_update',
    ),
    path(
        'content/<int:id>/delete/',
        views.ContentDeleteView.as_view(),
        name='module_content_delete',
    ),
    path(
        'lesson/<int:lesson_id>/step/<model_name>/create/',
        views.StepCreateUpdateView.as_view(),
        name='lesson_step_create',
    ),
    path(
        'lesson/<int:lesson_id>/step/<model_name>/<id>/',
        views.StepCreateUpdateView.as_view(),
        name='lesson_step_update',
    ),
    path(
        'step/<int:id>/delete/',
        views.StepDeleteView.as_view(),
        name='lesson_step_delete',
    ),
    path(
        'module/<int:module_id>/',
        views.ModuleContentListView.as_view(),
        name='module_content_list',
    ),
    path(
        'lesson/<int:lesson_id>/',
        views.LessonStepListView.as_view(),
        name='lesson_step_list',
    ),
    path(
        'module/order/',
        views.ModuleOrderView.as_view(),
        name='module_order',
    ),
    path(
        'lesson/order/',
        views.LessonOrderView.as_view(),
        name='lesson_order',
    ),
    path(
        'step/order/',
        views.StepOrderView.as_view(),
        name='step_order',
    ),
    path(
        'submission/<int:pk>/status/',
        views.PracticalSubmissionUpdateView.as_view(),
        name='submission_status_update',
    ),
    path(
        'assignment/<int:assignment_id>/submissions/',
        views.AssignmentSubmissionListView.as_view(),
        name='assignment_submission_list',
    ),
    path(
        'content/order/',
        views.ContentOrderView.as_view(),
        name='content_order',
    ),
    path(
        'subject/<slug:subject>/',
        views.CourseListView.as_view(),
        name='course_list_subject',
    ),
    path(
        '<slug:slug>/',
        views.CourseDetailView.as_view(),
        name='course_detail',
    ),
]
